# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59eb449833b677db6ac33e6a3bee4f230bfab18f9f2fff72e2d8efd304b7fc937082fa47aa4511f0fd05930df051c4f6e4c3cffe1825e498fe55f4758132006b

test:
  secret_key_base: 77d999484951fd72cc046ef054aece62e1e2d273d4b045c414b6f650f674477b3191c835f522eff67b160445eaae49e06d24872573833815710ac6ab376fd8b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
